# optional addition of an http server for compatibility reasons
[http]
port = 8080
ip = "127.0.0.1"
threads = 1
logfile = "alternate_log.txt"
[http.resources]
root = "."
routes = ["*:https://localhost:4343"]

[ssl.resources]
root = "."
aliases = ["/test:/test.html", "/:/test.html"]
[ssl]
port = 4343
ip = "127.0.0.1"
threads = 10
logfile = "log.txt"
private_key = "privkey.pem"
certificate_chain = "certs.pem"
