[http]
port = 8080
ip = "0.0.0.0"
threads = 10
[http.resources]
root = "/rsweb"
index = "/"
aliases = ["/test:/test.html"]
[ssl]
port = 8080
ip = "0.0.0.0"
threads = 10
private_key = "/rsweb/privkey.pem"
certificate_chain = "/rsweb/certs.pem"
[ssl.resources]
root = "/rsweb"
index = "/test.html"
aliases = ["/test:/test.html"]
