port = 8080
ip = "0.0.0.0"
threads = 10
[resources]
root = "/rsweb"
index = "/test.html"
aliases = ["/test:/test.html"]
[ssl]
private_key = "/rsweb/privkey.pem"
certificate_chain = "/rsweb/certs.pem"
