port = 8080
ip = "127.0.0.1"
threads = 10
logfile = "log.txt"
[resources]
root = "."
index = "/test.html"
aliases = ["/test:/test.html"]
[ssl]
private_key = "privkey.pem"
certificate_chain = "certs.pem"
